noop-s:
	gcc -I ../lib ../lib/server_lib.c server_main_noop.c -o server.out
	./server.out 2009

noop-c:
	gcc -I ../lib ../lib/client_lib.c client_main_noop.c -o client.out
	./client.out 127.0.0.1 2009

c:
	rm *out
