all:
	gcc src/fputs_fgets.c -o bin/fputs_fgets.out
	gcc src/fputc_fgetc.c -o bin/fputc_fgetc.out

all2:
	mkdir -p bin
	gcc src/fgets.c -o bin/fgets.out

run:
	./bin/fputs_fgets.c.out
	./bin/fputc_fgetc.out
