t1a:
	echo Alice > file.txt
	echo Bob >> file.txt
	ls
	cat file.txt
	gcc ex1.c 
	./a.out 
	rm *.out *.txt

t1b:
	echo Alice > file.txt
	echo Bob >> file.txt
	echo Charlie >> file.txt
	echo David >> file.txt
	ls
	cat file.txt
	gcc ex1.c 
	./a.out 
	rm *.out *.txt

t2a:
	echo Alice >> file.txt
	cat file.txt
	gcc ex2.c
	./a.out file.txt
	ls
	cat file.txt
	rm *txt *out

t2b:
	ls
	gcc ex2.c
	./a.out file.txt
	ls
	cat file.txt
	rm *txt *out

