t2:
	touch file.txt
	ls 
	gcc permissions.c
	./a.out
	ls -al file.txt
	rm *out *txt
	
t1:
	touch file.txt
	mkdir dir1
	gcc file_type.c
	./a.out file.txt
	./a.out dir1
	./a.out .
	rm *txt *out 
	rm -r dir1
