t4:
	touch file.txt
	gcc access2.c
	./a.out
	cat file.txt
	rm *out *txt

t3:
	touch file.txt
	gcc access.c
	./a.out
	cat file.txt
	rm *out *txt

t2:
	touch file.txt
	ls 
	gcc permissions.c
	./a.out
	ls -al file.txt
	rm *out *txt
	
t1:
	touch file.txt
	mkdir dir1
	ls .
	gcc file_type.c
	./a.out file.txt
	./a.out dir1
	./a.out .
	./a.out ..
	rm *txt *out 
	rm -r dir1
