ex1:
	echo "10 20 30" > file.txt
	cat file.txt
	gcc ex1.c
	./a.out
	rm *txt *.out

ex2: 
	echo "10" > file.txt
	echo "20" >> file.txt
	echo "30" >> file.txt
	cat file.txt
	gcc ex2.c
	./a.out
	rm *txt *.out
